import NavigMenu from "@/components/NavigMenu";
import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import React from "react";
import {Toaster} from "@/components/ui/toaster";
import {ThemeProvider} from "next-themes";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
    <body>
    <ThemeProvider attribute="class" defaultTheme='system' enableSystem>
      <main className="flex min-h-screen w-full flex-col">
        <NavigMenu/>
        {children}
      </main>
    </ThemeProvider>
    <Toaster/>
    </body>
    </html>
  );
}
