services:
  be-app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:8080"

  fe-app:
    build:
      context: ../fe
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
