services:
  postgres:
    image: postgres:latest
    container_name: PostgresContainer
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  be-app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    restart: always
    ports:
      - "8080:8080"
    environment:
      DEV_MODE: true
      DATABASE_URL: postgresql://postgres:pass@postgres:5432/postgres?sslmode=disable
      JWT_SECRET: c8XNLEmoosvyhLxJCio2NAMAH26xX1iMNXTUDXV8y858wNrV5WHeQXT6vg4FrerLXzhRPm1jg3Q

  fe-app:
    build:
      context: ../fe
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_URL: http://localhost:8080

volumes:
  postgres_data:
    driver: local
